cuAStar.hpp
HOST_FUN
DEVICE_FUN
HOST_DEVICE_FUN
STB_IMAGE_WRITE_IMPLEMENTATION
CUDA_CHECK_ERROR
LOG_MESSAGE
const int threadsPerBlock
This is the default threads number, but you can choose up to 1024.
Referenced by array2PointCloudImg, array2PointCloudImgBound, enumerationSort.
__global__ void curandx(unsigned int seed, T *d_val)
Generates a random float between 0 and 1 with precision up to 1e-6.
Referenced by array2PointCloudImg, array2PointCloudImgBound, checkNodeExsist, computeHeuristicDistance, computeKnnNodes, computeNodeTrajectoryCost, computeOptimalNode, computePointCloudBoundBox, computeSortedNodes, computeTrajectoryCost, Node3d< T >::distanceTo, drawFilledCircle, drawFilledCircles, enumerationSort, enumerationSortNodes, getChunk, getChunkArray, getPlyPointNum, getRootNodes, hasOrphanNodes, Node3d< T >::isEqual, isPlyValid, Node3d< T >::Node3d, Node3d< T >::Node3d, readPlyNode, savePointCloudImage, updateNearest.
__device__ float fatomicMin(float *addr, float value)
implemntation of atomic min for float type as cuda do not support it original implentation by : https://forums.developer.nvidia.com/t/atomicmin-with-float/22033
Referenced by computePointCloudBoundBox.
__device__ float fatomicMax(float *addr, float value)
Referenced by computePointCloudBoundBox.
__device__ void atomicExchNode(NodeType *target, const NodeType &val)
bool isPlyValid(const std::string plyFilePath)
Check if a given point cloud data file .ply file path exists or not.
a user error to cmd in debug mode, else none.
References curandx, LOG_MESSAGE.
Referenced by getPlyPointNum, readPlyNode.
NodeType readPlyNode(const std::string &plyFilePath, const size_t idx)
extract a Node object from a .ply file defined by index idx, in the file, reprsent the line number of point coordiantes, it is computioanlly slow , not use in loops or other , just for single node extrcation, this method will be decapred in other versions
References curandx, isPlyValid, LOG_MESSAGE.
void drawFilledCircle(unsigned char *image, int width, int height, const Circle *circle, const Color *color)
Draw a 2D sphere (plain circle) given radius, center, and color.
References curandx.
Referenced by drawFilledCircles.
void drawFilledCircles(unsigned char *image, int width, int height, const int *centersX, const int *centersY, const unsigned char *colorsR, const unsigned char *colorsG, const unsigned char *colorsB, int numCircles, double radiusRatio)
Draw a sample of point cloud nodes as 2D colored circles.
References curandx, drawFilledCircle.
Referenced by savePointCloudImage.
void savePointCloudImage(const char *filePath, int width, int height, const int *centersX, const int *centersY, const unsigned char *colorsR, const unsigned char *colorsG, const unsigned char *colorsB, int numCircles, double radiusRatio)
Draw and save a given 2D points cloud of nodes as an image.
References curandx, drawFilledCircles.
Referenced by array2PointCloudImg, array2PointCloudImgBound.
__global__ void computePointCloudBoundBox(const NodeType *h_arrayNodes, int N, float *minX, float *maxX, float *minY, float *maxY)
compute the 2d bound box dimension for 2d plotting scaling issues for N nodes elments the minimal block grid number is : (N + thredsPerBlock - 1) / thredsPerBlock; interblock synhonization , usen shared memory Thread 0 of each block updates the global min/max values using atomic operations note we cannot template the function with double , because cuda cannot use atomic operation for doubles , just for cuda computation cabolit >6.0 see: https://forums.developer.nvidia.com/t/atomic-functions-for-double-precision/9963 https://forums.developer.nvidia.com/t/why-does-atomicadd-not-work-with-doubles-as-input/56429 atomic operations is only supported by devices of compute capability 5.0 and higher.
TodoUse of Local Reductions per Block
References curandx, fatomicMax, fatomicMin.
void array2PointCloudImg(const NodeType *h_arrayNodes, int numNodes, const char *pngFilePath, double scaleFactor=100, double radiusRatio=0.01)
Draw and save a given 2D point cloud of nodes as an image, the data is given as a 1d host array of NodeType template objects.
scaleFactor : zoom image coffienct radiusRatio :
References curandx, savePointCloudImage, threadsPerBlock.
void array2PointCloudImgBound(const NodeType *h_arrayNodes, int numNodes, const char *pngFilePath, NodeType *startNode, NodeType *endNode, int scaleFactor=100, double radiusRatio=0.01)
References curandx, savePointCloudImage, threadsPerBlock.
size_t getPlyPointNum(const std::string plyFilePath)
Return the number of points stored in a .ply file.
References curandx, isPlyValid.
__global__ void enumerationSort(T *a, int N, T *b)
CUDA kernel for sorting a numerical array using the enumeration sort algorithm. Original implementation by: Meng Hongyu, Guo Fangjin, UCAS, China https://arxiv.org/pdf/1505.07605 Modified by: Wissem Chiha, 01-09-2024, using templates.
References curandx, threadsPerBlock.
__global__ void enumerationSortNodes(NodeType *d_nodesArray, int N, int ax, NodeType *d_nodesArraySorted)
CUDA kernel that sorts an array of nodes based on a specified axis. This kernel sorts the nodes in ascending order according to their value along the given axis (1: x, 2: y, 3: z).
d_nodesArray Device pointer to the array of nodes to be sorted. ax Axis to sort by (1: x, 2: y, 3: z). N Number of nodes in the array. d_nodesArraySorted Device pointer to the array where sorted nodes will be stored. the call of this kernel with ax = 3 and Node2d class has no effect, and it do not throw any error
References curandx.
void updateNearest(NodeType *nearestNodes, T *distances, const NodeType &node, const NodeType &otherNode, int k)
Update nearest neighbors list if the new node is closer
References curandx.
Referenced by computeKnnNodes.
__global__ void computeKnnNodes(NodeType *d_sortedX, NodeType *d_sortedY, NodeType *d_sortedZ, NodeType targetNode, int N, int k, int range, NodeType *d_kNodes)
Computes the K-nereast neighoods of a given node in a device array structure , by sorting x, y, z attributes, without using the K-D tree this kernel should excute on 1 block, so the maxium nodes number sorted arrays is 1024.
range control the exploration range of the KNN, fixed , adjustee based on the point cloud distribution density , low for high dense data and high for low dense distrubution k should be < threadsPerBlock
References curandx, updateNearest.
__global__ void checkNodeExsist(const NodeType *d_nodesArray, int numNodes, const NodeType *nodeToCheck, int *status)
Checks if a given node exists in the device nodes array.
This method will be deprecated in future versions. we use atomic exchange to ensure thred safty writtin value to the we reprsent by : 0 FALSE and any other int the TRUE value, perform chek if only nly perform check if the index is within bounds and status is still false (0)
References curandx.
void computeHeuristicDistance(const NodeType &node, const NodeType &targetNode, T *hfun)
heuristic function which computes the estimated cost to the goal node, starting from the current given node, it simply the euclidian distances or the manthetn distance could be used
References curandx.
Referenced by computeNodeTrajectoryCost.
void computeNodeTrajectoryCost(const NodeType &node, const NodeType &targetNode, T *p_cost_)
Computes the trajectory cost metric starting from a given node. The objective function is: f(n) = g(n) + h(n), where g(n) is the path cost from the start node to the current node, and h(n) is the heuristic function value.
node The current node representing the position in the trajectory.
References computeHeuristicDistance, curandx.
__global__ void computeSortedNodes(const NodeType *d_knnNodesArray, int k, const NodeType *endNode, NodeType *d_sortedNodesArray)
sort the knn nodes based on path metric f(n) = g(n) + h(n) from the k nearest neighbor nodes. Each thread will compute the trajectory cost and then determine the node with the minimum cost.
This function is designed to execute within a single block, no interblock synchinoziation is implemented d_sortedNodesArray array of k-nearest neighbor nodes of the current node to be checked. The maximum size is 1024.
References curandx.
void computeTrajectoryCost(const NodeType *d_tarjNodesArray, int N, T *cost_)
Given a trajectory path represented by a device array of nodes, it computes the path cost: the Euclidean distance between the start and destination nodes. The start node is the first node in the array, and the destination node is the last node.
Boundary checks are not performed; N is assumed to be within the array size range.
References curandx.
__global__ void smoothTrajectory(const NodeType *d_trajNodesArray, int N, int k, NodeType *d_trajNodesArraySmooth)
soothing the distcreate computed trajectory, using either spline basis or bezier curves , or just normale interpolations.
N number of points or control points in the trajectory k number of the evaulation point of the new trajectory
__global__ void getRootNodes(const NodeType *d_nodesArray, int numNodes, NodeType *d_rootsArray)
Extracts nodes without a parent from an array of N nodes. Iterates over the input array, where each node has a p_node attribute (pointer to its parent). Constructs a new array containing only nodes where p_node == nullptr (i.e., no parent).
References curandx.
__global__ void hasOrphanNodes(const NodeType *d_nodesArray, int N, bool *status)
Given an array of nodes, checks if there are any nodes without a parent, referred to as orphan nodes. Each thread in each block checks its assigned node.
N The number of nodes. status A boolean flag to indicate if an orphan node is found.
References curandx.
__global__ void getChunkArray(const NodeType *d_nodesArray, int N, int chunkSize, int index, NodeType *d_chunkArray)
given an array of nodes, extracts the elements starting from chunkSize * index to chunkSize * (index + 1) and fills d_chunkArray with them.
NodeType Type of the node elements. d_nodesArray The input array of nodes. N The total number of elements in d_nodesArray. chunkSize The size of the chunk to extract. index The chunk index to extract. d_chunkArray The output array to store the extracted chunk.
References curandx.
void getChunk(const NodeType *nodesArray, int N, int chunkSize, int index, NodeType *chunkArray)
References curandx.
__global__ void computeOptimalNode(const NodeType *d_nodesArray, int k, const NodeType *endNode, NodeType *d_bestNode)
Computes the best successor node based on path metric f(n) = g(n) + h(n) from the k nearest neighbor nodes. Each thread will compute the trajectory cost and then determine the node with the minimum cost. This function is designed to execute within a single block.
d_nodesArray Array of k-nearest neighbor nodes of the current node to be checked. The maximum size is 1024.
References curandx.